MADWORDS/Models/ErrorViewModel.cs
using System;

namespace MADWORDS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MADWORDS/Models/Madword.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MADWORDS.Models
{
    public class Madword
    {
        //this MadwordID will become the primary key
        // Add ID to the key. EF knows the convention and makes it primary key
        public int MadwordID { get; set; }
        public string MadwordTitle { get; set; }
        public string MadwordTopic { get; set; }
        public string AuthorName { get; set; }
        public int MadwordRating { get; set; }

        // Has-a relationship
        // when EF creates the table, it will automatically create foreign key because of this
        public User Author { get; set; }
        public string MadwordText { get; set; }
        public DateTime MadwordDate { get; set; }
    }
}

MADWORDS/Models/MadwordContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MADWORDS.Models
{
    public class MadwordContext : DbContext
    {
        public MadwordContext(DbContextOptions<MadwordContext> options) : base(options) { }

        public DbSet<Madword> Madwords { get; set; }
        public DbSet<User> User { get; set; }

    }
}

MADWORDS/Models/Update.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MADWORDS.Models
{
    public class Update
    {
        //this MadwordID will become the primary key
        // Add ID to the key. EF knows the convention and makes it primary key
        public int UpdateID { get; set; }
        public string UpdateTitle { get; set; }

        // Has-a relationship
        // when EF creates the table, it will automatically create foreign key because of this
        public string UpdateText { get; set; }
        public DateTime UpdateDate { get; set; }
    }
}

MADWORDS/Models/UpdateContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MADWORDS.Models
{
    public class UpdateContext : DbContext
    {
        public UpdateContext(DbContextOptions<UpdateContext> options) : base(options) { }

        public DbSet<Update> Updates { get; set; }

    }
}

MADWORDS/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MADWORDS.Models
{
    public class User
    {
        // userID will become primary key
        public int UserID { get; set; }
        public string Name { get; set; }
    }
}

MADWORDS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MADWORDS.Models;

namespace MADWORDS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MADWORDS/Controllers/MadwordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MADWORDS.Models;
using MADWORDS.Repos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MADWORDS.Controllers
{
    public class MadwordController : Controller
    {
        IMadwordRepository repo;

        public MadwordController(IMadwordRepository r)
        {
            repo = r;
        }

        public IActionResult Index()
        {
            //get all madwords in the database
            //List<Madword> madwords = repo.Madwords.ToList<Madword>(); // Use ToList to convert the IQueryable to a list
            var madwords = (from r in repo.Madwords orderby r.MadwordDate descending select r).ToList();

            return View(madwords);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Madword model)
        {
            model.MadwordDate = DateTime.Now;
            model.MadwordRating = 1;
            // Store the model in the database
            repo.AddMadword(model);
            return View(model);
        }

        public IActionResult Madwords()
        {
            //get all madwords in the database
            List<Madword> madwords = repo.Madwords.ToList<Madword>(); // Use ToList to convert the IQueryable to a list

            return View(madwords);
        }

        [HttpPost]
        public IActionResult Index(string madwordSearch)
        {
            var madwordsList = (from r in repo.Madwords where r.MadwordText.Contains(madwordSearch) || r.MadwordTitle.Contains(madwordSearch) || r.Author.Name.Contains(madwordSearch) orderby r.MadwordDate descending select r).ToList();

            return View(madwordsList);
        }
    }
}

MADWORDS/Controllers/UpdatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MADWORDS.Models;
using MADWORDS.Repos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MADWORDS.Controllers
{
    public class UpdatesController : Controller
    {
        IUpdateRepository repo;

        public UpdatesController(IUpdateRepository r)
        {
            repo = r;
        }

        public IActionResult Index()
        {
            //get all updates in the database
            //List<Update> updates = repo.Updates.ToList(); // Use ToList to convert the IQueryable to a list
            var updates = (from u in repo.Updates orderby u.UpdateDate descending select u).ToList();
            return View(updates);
        }

        public IActionResult NewUpdate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewUpdate(Update model)
        {
            model.UpdateDate = DateTime.Now;
            // Store the model in the database
            repo.AddUpdate(model);

            return View(model);
        }
    }
}

MADWORDS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "MADWORDS";

    var random = new Random();
    string[] write = { "Write", "Scribble", "Create", "Compose", "Sling", "Shoot", "Journal", "Ink", "Jot down", "Sign", "Scrawl" };
    string writeTitle = write[random.Next(write.Length)];

    ViewData["Create"] = writeTitle + " some MADWORD";
}

<div class="text-center">
    <h1 class="pt-4">Welcome to MADWORDS</h1>
    <p class="lead p-4">The website that lets you make crazy stories. Have fun reading others peoples MADWORDS or create your own! Just enter in the types of words the game asks for and when you're all done hit submit.</p>
    <br />
    <p><a class="nav-link text-white btn btn-primary btn-lg" asp-area="" asp-controller="Madword" asp-action="Create">Make your own MADWORD</a></p>
    <p><a class="nav-link text-white btn btn-primary btn-lg" asp-area="" asp-controller="Madword" asp-action="Index">Read other peoples MADWORDS</a></p>
</div>

MADWORDS/Views/Madword/Create.cshtml
@model Madword

@{
    var random = new Random();
    string[] write = { "Write", "Scribble", "Create", "Compose", "Sling", "Shoot", "Journal", "Ink", "Jot down", "Sign", "Scrawl" };
    string writeTitle = write[random.Next(write.Length)];

    ViewData["Title"] = writeTitle + " some MADWORD";
}

<div class="text-center">
    @if (Model != null)
    {
        <h1 class="jumbotron">Your MADWORD</h1>
        <div>
            <h3>@Model.MadwordTitle</h3>
            <p><strong>@Model.MadwordText</strong></p>
            <p>By @Model.Author.Name</p>
            <p><small>@Model.MadwordDate</small></p>
        </div>

        <div class="container mt-3 p-5 text-center">
            <a class="nav-link text-dark" asp-area="" asp-controller="Madword" asp-action="Create"><strong>MAKE MORE WORD</strong></a>
        </div>
    }
    else
    {
        <h1 class="jumbotron">@ViewData["Title"]</h1>

        <form method="post">
            <div class="row p-2 text-justify">
                <div class="col-sm-3 my-1">
                    <h3>Author</h3>
                    <input asp-for="Author.Name" class="form-control col-sm-9 col-md-11" required />
                </div>
            </div>
            <div class="row p-2 text-justify">
                <div class="col-sm-3 my-1">
                    <h3>MADWORD</h3>
                </div>
            </div>
            <div class="form-row align-items-center" id="madwords">

            </div>
            <div class="row p-2 text-justify">
                <div class="col-sm-6 my-1">
                    <h3>Title</h3>
                    <p>Title your MADWORD based on the words you entered.</p>
                    <input asp-for="MadwordTitle" class="form-control col-sm-9 col-md-11 titleword" id="Title" placeholder="" required />
                </div>
            </div>
            <div class="row p-2 text-justify">
                <div class="col-sm-3 my-1">
                    <button type="submit" class="btn btn-primary" id="submitbtn">Submit</button>
                </div>
            </div>
            <input asp-for="MadwordText" type="text" id="words" hidden />
        </form>
    }
</div>


@section Scripts
{
    <script>
        var stories = {
            "story": [
                {
                    "text": "Somebody once told me the * is gonna * me, I ain't the * * in the *, She was looking kind of * with her * and her * in the shape of a * on her *",
                    "blanks": ["Noun", "Verb", "Adjective", "Noun", "Place", "Adjective", "Noun", "Noun", "Letter", "Noun"]
                },
                {
                    "text": `* the *-nosed * had a very * nose, And if you ever * it, You would even say it glows, All of the other * used to * and call him *, They never let * * * in any * games`,
                    "blanks": ["Name", "Adjective", "Noun", "Adjective", "Verb", "Noun", "Verb", "Noun", "Adjective", "Name", "Verb", "Adjective"]
                },
                {
                    "text": `The majestic * has roamed the forests of * for thousands of years. Today, it wanders in search of *. It must find * to survive the harsh *.`,
                    "blanks": ["Animal", "Country", "Noun", "Noun", "Season"]
                },
                {
                    "text": `He was a *, She was a *. Can I make it any more obvious? He was a *, She did *. What more can I say? He wanted *, She'd never tell. Secretly she * * as well. But all of her *, Stuck up their *, They had a problem with his * *.`,
                    "blanks": ["Noun", "Noun", "Noun", "Sport", "Noun", "Verb (past tense)", "Noun", "Noun", "Noun", "Adjective", "Noun (plural)"]
                },
                {
                    "text": `All the * *, true care truth brings. I'll * one *. Your *, * *. Always I know, you'll be at my *. *, *, *`,
                    "blanks": ["Adjective", "Noun (plural)", "Verb", "Noun", "Noun", "Adjective", "Noun", "Place", "Verb (ending w/ -ing)", "Verb (ending w/ -ing)", "Verb (ending w/ -ing)"]
                },
                {
                    "text": `I wish you would * back from that * my friend. You could * with all the * that you've been * in. And if you do not want to * me again, I would understand, I would understand`,
                    "blanks": ["Verb", "Noun", "Verb", "Noun (plural)", "Verb (ending w/ -ing)", "Verb"]
                }
            ]
        }

        let storyNumber = Math.floor((Math.random() * stories.story.length));
        stories.story[storyNumber].blanks.forEach(addWord);

        function addWord(item, index) {
            document.getElementById("madwords").innerHTML += `
            <div class="col-sm-3 my-1">
                <label>${item}</label>
                <input type="text" class="form-control word" placeholder="" required>
            </div>
            `;
        }

    </script>
}

MADWORDS/Views/Madword/Index.cshtml
@model List<Madword>

@{ ViewData["Title"] = "MADWORDS"; }


@if (Model.Count != 0)
{


<nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item pr-3">
                <a asp-action="Index" class="nav-link active">All<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a asp-action="Top10" class="nav-link disabled">Top 10<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <form method="post" class="form-inline my-2 my-lg-0">
            <label for="madwordSearch" class="control-label" hidden>Title</label>
            <input class="form-control mr-sm-2" type="search" name="madwordSearch" placeholder="Search for title, author, or text" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
}

@foreach (Madword madword in Model)
{
<div class="container mt-3 shadow p-5 text-left">
    <h3>@madword.MadwordTitle</h3>
    <p>By @madword.Author.Name - <small>@madword.MadwordDate</small></p>
    <p><strong>@madword.MadwordText</strong></p>
    <p>Votes: @madword.MadwordRating <a href="">👍</a></p>
</div>}

@if (Model.Count == 0)
{
<div class="container mt-3 p-5 text-center">
    <p>Nobody's written a MADWORD yet.</p>
    <a class="nav-link text-dark" asp-area="" asp-controller="Madword" asp-action="Create"><strong>BE THE FIRST</strong></a>
</div>}

MADWORDS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MADWORDS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Madword" asp-action="Create">Create a MADWORD</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Madword" asp-action="Index">View MADWORDS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Updates" asp-action="Index">Updates</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-white shadow-lg">
        <main role="main" class="pb-3 pt-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-black-50 bg-white">
        <div class="container">
            &copy; 2020 - Joseph Sepe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MADWORDS/Views/Updates/Index.cshtml
@model List<Update>

@{
    ViewData["Title"] = "Updates";
}

@foreach (Update update in Model)
{
    <div class="container mt-3 shadow p-5 text-left">
        <h4>@update.UpdateTitle</h4>
        <p><small>@update.UpdateDate</small></p>
        <p>@update.UpdateText</p>
    </div>
}

@if (Model.Count == 0)
{
<div class="container mt-3 p-5 text-center">
    <p>There aren't any updates yet.</p>
</div>}

MADWORDS/Views/Updates/NewUpdate.cshtml
@model Update
@{
   ViewData["Title"] = "MADWORDS - Post Update";
}

<div class="text-center">
    <h1 class="jumbotron">Post an Update</h1>
    <form method="post" class="container">
        <div class="row p-2 text-justify">
            <label asp-for="UpdateTitle" class="control-label col-sm-3 col-md-1">Title</label>
            <input asp-for="UpdateTitle" class="form-control col-sm-9 col-md-11" />
        </div>
        <div class="row p-2 text-justify">
            <label asp-for="UpdateText" class="control-label col-sm-3 col-md-1">Text</label>
            <textarea asp-for="UpdateText" class="form-control col-sm-9 col-md-11"></textarea>
        </div>

        <div class="row p-2">
            <div class="col-10"></div>
            <button type="submit" class="form-control btn btn-success col-2">Submit</button>
        </div>
    </form>
    @if (Model != null)
    {
        <div class="container mt-3 shadow p-5 text-left">
            <h4>@Model.UpdateTitle</h4>
            <p><small>@Model.UpdateDate</small></p>
            <p><strong>Story: </strong>@Model.UpdateText</p>
        </div>
    }
    </div>